use std::fmt::{Debug, Display};

use anyhow::{Error as E, Result};

use candle_transformers::models::qwen2::{Config as Qwen2Config, ModelForCausalLM as Qwen2};
use candle_transformers::models::qwen3::{Config as Qwen3Config, ModelForCausalLM as Qwen3};

use candle_core::{DType, Device, Tensor};
use candle_nn::VarBuilder;
use candle_transformers::generation::LogitsProcessor;
use ggmath::random::ToSeed;
use hf_hub::api::sync::Api;
use tokenizers::Tokenizer;

use crate::chat::{Chat, ChatRole};
use crate::inference::InferIter;
use crate::model_type::ModelType;
use crate::token_string::{IntoTokenString, TokenString};

pub const MAX_TOKENS: usize = 2048;

#[derive(Clone)]
pub struct Model {
    model_type: ModelType,
    config: DynConfig,
    vb: VarBuilder<'static>,
    tokenizer: Tokenizer,
    vocab_size: usize,
    device: Device,
    seed: u64,
}

impl Model {
    pub fn new(model_type: ModelType, seed: u64, use_cuda: bool) -> Result<Self> {
        let device = if use_cuda && candle_core::utils::cuda_is_available() {
            Device::new_cuda(0).unwrap()
        } else {
            Device::Cpu
        };
        let api = Api::new()?;
        let tokenizer_repo = api.model(model_type.tokenizer_repo().to_string());
        let model_repo = api.model(model_type.model_repo().to_string());

        // Create model config
        let config = model_type.create_config(&model_repo);

        // Get the tokenizer and model files
        let tokenizer_filename = tokenizer_repo.get(model_type.tokenizer_json_name())?;
        let model_filenames = model_type
            .model_names()
            .iter()
            .map(|name| model_repo.get(name))
            .collect::<Result<Vec<_>, _>>()?;

        // Create VarBuilder
        let vb =
            unsafe { VarBuilder::from_mmaped_safetensors(&model_filenames, DType::F32, &device)? };

        // Create tokenizer
        let tokenizer = Tokenizer::from_file(tokenizer_filename).map_err(E::msg)?;
        let vocab_size = tokenizer.get_vocab_size(false);

        Ok(Self {
            model_type,
            config,
            vb,
            tokenizer,
            device: device.clone(),
            vocab_size,
            seed,
        })
    }

    pub fn model_type(&self) -> &ModelType {
        &self.model_type
    }

    pub fn seed(&self) -> u64 {
        self.seed
    }

    pub fn set_seed(&mut self, seed: u64) {
        self.seed = seed;
    }

    pub fn max_tokens(&self) -> usize {
        MAX_TOKENS
    }

    pub fn new_token_string(&self) -> TokenString {
        TokenString::new(Vec::new(), self.clone())
    }

    pub fn tokenize_str(&self, text: impl Display) -> TokenString {
        // Tokenize the text
        let tokens = self.tokenizer.encode(text.to_string(), true).unwrap();

        // Get the token ids
        let token_ids = tokens.get_ids().to_vec();
        TokenString::new(token_ids, self.clone())
    }

    pub fn tokenize(&self, text: impl IntoTokenString) -> TokenString {
        text.into_token_string(self)
    }

    pub(crate) fn detokenize(&self, tokens: impl AsRef<[u32]>) -> String {
        // Decode the tokens into a string
        let text = self
            .tokenizer
            .decode(tokens.as_ref(), true)
            .map_err(E::msg)
            .unwrap();
        text
    }

    /// Attempt to get the token for a given string
    pub(crate) fn get_token(&self, s: impl Display) -> Result<u32> {
        match self.tokenizer.get_vocab(true).get(&s.to_string()) {
            Some(token) => Ok(*token),
            None => anyhow::bail!("cannot find the token for {:?}", s.to_string()),
        }
    }

    /// Get an iterator that yields tokens generated by the model.
    /// Returns an error if the prompt is empty.
    pub fn infer_iter(
        &self,
        prompt: impl IntoTokenString,
        seed: u64,
        temp: Option<f64>,
        top_p: Option<f64>,
        repeat_penalty: f32,
        repeat_last_n: usize,
    ) -> Result<InferIter> {
        // Add the model seed to the seed provided
        let seed = seed.wrapping_add(self.seed);

        // Tokenize the prompt
        let prompt = self.tokenize(prompt);

        // Fail if the prompt is empty
        if prompt.is_empty() {
            anyhow::bail!("prompt was empty")
        }

        // Create pipeline
        let pipeline = self
            .model_type
            .create_pipeline(&self.config, self.vb.clone());

        // Create logits processor
        let logits_processor = LogitsProcessor::new(seed, temp, top_p);

        // Get the end of text token
        let eos_token = self
            .get_token("<|im_end|>")
            .or_else(|_| self.get_token("<|endoftext|>"))
            .unwrap();

        // Create the iterator
        Ok(InferIter::new(
            self.model_type.clone(),
            self.device.clone(),
            prompt,
            self.vocab_size,
            pipeline,
            logits_processor,
            repeat_penalty,
            repeat_last_n,
            eos_token,
        ))
    }

    /// Generate a response message based on the chat history.
    pub fn chat(
        &self,
        chat: &Chat,
        sender: ChatRole,
        think: bool,
        seed: u64,
        temp: Option<f64>,
        top_p: Option<f64>,
        repeat_penalty: f32,
        repeat_last_n: usize,
    ) -> InferIter {
        // Panic if the model type does not support chat
        if !self.model_type.can_chat() {
            panic!("Model type {:?} does not support chat", self.model_type);
        }

        // Generate the basic chat prompt
        let prompt = self.model_type.create_chat_prompt(chat, sender, think);

        self.infer_iter(
            prompt,
            seed,
            temp,
            top_p,
            repeat_penalty,
            repeat_last_n,
        )
        .unwrap()
    }

    /// Predict the text which follows the given prompt.
    pub fn predict_next(
        &self,
        prompt: impl IntoTokenString,
        seed: u64,
        temp: Option<f64>,
        top_p: Option<f64>,
        repeat_penalty: f32,
        repeat_last_n: usize,
    ) -> InferIter {
        self.infer_iter(
            prompt,
            seed,
            temp,
            top_p,
            repeat_penalty,
            repeat_last_n,
        )
        .unwrap()
    }

    /// Generate a string similar to the given example strings.
    pub fn generate_similar(
        &self,
        desired_traits: impl Display,
        examples: &[impl Display],
        seed: u64,
        temp: Option<f64>,
    ) -> String {
        const EXAMPLE_DROP_RATE: f64 = 0.25;
        const MIN_EXAMPLES: usize = 3;

        // Convert the examples to strings
        let mut examples: Vec<String> = examples.iter().map(|e| e.to_string()).collect();

        // If temp is provided, or EXAMPLE_DROP_RATE is larger than 0.0, shuffle the examples by sorting by random values generated from the seed
        // This should help introduce more variety if desired
        if temp.is_some() || EXAMPLE_DROP_RATE > 0.0 {
            let mut example_drop_seed = seed;
            examples.sort_by_key(|_| {
                let key = example_drop_seed.into_random::<u32>();
                example_drop_seed = example_drop_seed.wrapping_add(1);
                key
            });
        }

        // Optionally drop some of the examples based on EXAMPLE_DROP_RATE
        if EXAMPLE_DROP_RATE > 0.0 {
            // Calculate the number of examples to keep based on the drop rate
            let number_to_keep = (((1.0 - EXAMPLE_DROP_RATE) * examples.len() as f64).floor()
                as usize)
                .max(MIN_EXAMPLES);

            // Keep only the first `number_to_keep` examples
            examples.truncate(number_to_keep);
        }

        // Create the chat with the desired traits and examples given as chat messages
        let mut chat = Chat::new();
        chat.add_message(
            ChatRole::User,
            format!(
                "I'm looking for things that could be described as \"{}\". Please provide an example.",
                desired_traits
            ),
        );
        let mut first_example = true;
        for example in examples {
            // If this is not the first example, insert a user message asking for another example
            if !first_example {
                chat.add_message(ChatRole::User, "Please provide another.".to_string());
            }
            first_example = false;
            chat.add_message(
                ChatRole::Model,
                format!("Here's an example like you described: [{}]", example),
            );
        }

        // Set the response prefix to "[" to encourage generating a "]"
        chat.set_response_prefix(Some("Here's an example like you described: [".to_string()));

        self.chat(&chat, ChatRole::Model, false, seed, temp, None, 1.1, 128)
            .complete(&["]", "\n"])
            .0
    }

    /// Summarize a string using the model.
    pub fn summarize(&self, text: impl AsRef<str>, seed: u64, temp: Option<f64>) -> String {
        let text = text.as_ref();
        let mut chat = Chat::new();

        // Set the system prompt to tell the model what its role should be
        chat.set_system_prompt(
            "You are an assistant whose job is to summarize text provided by the user. Keep it brief and concise, and wrap your summary in double quotes.",
        );

        // Add a user message asking the model to summarize the text
        chat.add_message(
            ChatRole::User,
            format!("Please summarize the following text:\n{}", text),
        );

        // Set the response prefix to avoid extra fluff
        chat.set_response_prefix(Some(
            "Certainly, here is my summary of the text you provided:\n\"".to_string(),
        ));

        self.chat(&chat, ChatRole::Model, false, seed, temp, None, 1.0, 0)
            .complete(&["\"", "\n"])
            .0
    }

    /// Summarize a string while forcing it into the given token count.
    /// If summarizing to this size fails, attempts for 'attempts' times.
    /// On a total failure, returns `None`.
    pub fn try_summarize_to_tokens(
        &self,
        text: impl AsRef<str>,
        token_count: usize,
        seed: u64,
        mut temp: f64,
        attempts: usize,
    ) -> Option<String> {
        let text = text.as_ref();

        // Look for a summary for `attempts` times
        for attempt in 0..attempts {
            // Attempt summarization and get token length
            let summary = self.summarize(text, seed.wrapping_add(attempt as u64), Some(temp));
            let summary_tokens = self.tokenize_str(&summary).len();

            if summary_tokens <= token_count {
                return Some(summary);
            }

            temp += 0.1;
        }

        None
    }

    /// Summarize a string while forcing it into the given token count.
    /// If summarizing to this size fails, attempts for 'attempts' times.
    /// On a total failure, forcefully truncates the summary to the given token count.
    pub fn summarize_to_tokens(
        &self,
        text: impl AsRef<str>,
        token_count: usize,
        truncate_towards_end: bool,
        seed: u64,
        mut temp: f64,
        attempts: usize,
    ) -> String {
        let text = text.as_ref();

        // Look for a summary for `attempts` times
        let mut summary = String::new();
        for attempt in 0..attempts {
            // Attempt summarization and get token length
            summary = self.summarize(text, seed.wrapping_add(attempt as u64), Some(temp));
            let summary_tokens = self.tokenize_str(&summary).len();

            if summary_tokens <= token_count {
                return summary;
            }

            temp += 0.1;
        }

        // If we couldn't get a summary within the token count, truncate the last summary
        let mut tokens = self.tokenize_str(&summary);
        if truncate_towards_end {
            tokens.truncate_rev(token_count);
        } else {
            tokens.truncate(token_count);
        }

        let truncated = self.tokenize(tokens);
        truncated.to_string()
    }

    /// Expand a string with more detail using the model.
    pub fn expand(&self, text: impl AsRef<str>, seed: u64, temp: Option<f64>) -> String {
        let text = text.as_ref();
        let mut chat = Chat::new();

        // Set the system prompt to tell the model what its role should be
        chat.set_system_prompt(
            "You are an assistant whose job is to expand text provided by the user with more detail.",
        );

        // Add a user message asking the model to expand the text
        chat.add_message(
            ChatRole::User,
            format!(
                "Please expand the following text with more detail: \"{}\"",
                text
            ),
        );

        // Set the response prefix to avoid extra fluff
        chat.set_response_prefix(Some("Here is the expanded text: \"".to_string()));

        self.chat(&chat, ChatRole::Model, false, seed, temp, None, 1.1, 64)
            .complete(&["\"", "\n"])
            .0
    }

    /// Given a list of items and a context string, try to choose the most appropriate item
    /// based on the context.
    /// Returns the chosen item (lowercased and trimmed) if successful, otherwise None.
    pub fn try_choose_item(
        &self,
        desired_traits: impl Display,
        items: impl IntoIterator<Item = impl Display>,
        seed: u64,
        temp: f64,
        attempts: usize,
    ) -> Option<String> {
        // Make sure that seed + attempts doesn't overflow by subtracting u64::MAX / 2
        let seed = if seed > u64::MAX - attempts as u64 {
            seed - u64::MAX / 2
        } else {
            seed
        };

        // Trim and lowercase all the items
        let items: Vec<String> = items
            .into_iter()
            .map(|item| item.to_string().trim().to_lowercase())
            .collect();

        // Join the items into a comma-separated list
        let items_string = format!("[\"{}\"]", items.join("\", \""));

        // Create the chat with the context, desired traits, and items
        let mut chat = Chat::new();

        // Set the system prompt to tell the model what its role should be
        chat.set_system_prompt(
            "You are an assistant whose job is to help the user choose things from a list based on their given criteria.",
        );

        // Set the item list in extra data
        chat.extra_data_mut()
            .insert("List".to_string(), items_string.into());

        // Add the user's messages with the desired traits and items
        chat.add_message(
            ChatRole::User,
            format!(
                "Tell me which item or thing in List you would describe as \"{}\"?",
                desired_traits
            ),
        );

        // Set the response prefix to end with a " so the model generates another "
        chat.set_response_prefix(Some("The closest item in List is \"".to_string()));

        // Create the prompt from the chat
        let prompt = self.model_type.create_chat_prompt(&chat, ChatRole::Model, false);

        // Keep trying until the model chooses an item, incrementing the seed each time
        // After each attempt, temperature is increased to encourage diversity
        let mut response = None;
        let mut temperature = temp;
        for seed in seed..seed + attempts as u64 {
            // Clone the items
            let mut possible_items = items.clone();

            // Begin inference
            let mut inference = self
                .infer_iter(prompt.clone(), seed, Some(temperature), None, 1.0, 0)
                .unwrap();

            // Infer while possible_items > 1
            let mut inferred = String::new();
            while possible_items.len() > 1 {
                // Attempt to get the next token and check if it matches any of the possible items
                if let Some(next_token) = inference.next_token() {
                    // Add the token to the inferred string
                    inferred.push_str(&self.detokenize(&[next_token]));

                    // Remove the item from the list if it doesn't begin with the inferred string
                    let formatted = inferred.trim().to_lowercase();
                    possible_items.retain(|item| item.starts_with(&formatted));
                }
                // If there are no more tokens, empty the possible items and break
                else {
                    possible_items.clear();
                    break;
                }
            }

            // If there is only one item left, return it
            if possible_items.len() == 1 {
                response = Some(possible_items.pop().unwrap());
                break;
            }

            // Raise the temperature and try again
            temperature += 0.1;
        }

        // Return the response
        response
    }
}

/// Contains a pipeline, could be one of multiple types.
pub enum Pipeline {
    Qwen2(Qwen2),
    Qwen3(Qwen3),
}

impl Pipeline {
    pub fn forward(&mut self, xs: &Tensor, start_pos: usize) -> Tensor {
        match self {
            Pipeline::Qwen2(qwen2) => qwen2.forward(xs, start_pos).unwrap(),
            Pipeline::Qwen3(qwen3) => qwen3.forward(xs, start_pos).unwrap(),
        }
    }
}

/// Contains a model config
#[derive(Debug, Clone)]
pub enum DynConfig {
    Qwen2(Qwen2Config),
    Qwen3(Qwen3Config),
}

impl DynConfig {
    pub fn as_qwen2(&self) -> Option<&Qwen2Config> {
        match self {
            DynConfig::Qwen2(config) => Some(config),
            _ => None,
        }
    }

    pub fn as_qwen3(&self) -> Option<&Qwen3Config> {
        match self {
            DynConfig::Qwen3(config) => Some(config),
            _ => None,
        }
    }
}
