use std::collections::HashMap;
use std::fmt::{Debug, Display};
use std::str::FromStr;

use anyhow::{Error as E, Result};

//use candle_transformers::models::mixformer::{Config, MixFormerSequentialForCausalLM as MixFormer};
use candle_transformers::models::phi::{Config as PhiConfig, Model as Phi};

use candle_core::{DType, Device, Tensor};
use candle_nn::VarBuilder;
use candle_transformers::generation::LogitsProcessor;
use ggmath::random::ToSeed;
use hf_hub::api::sync::Api;
use tokenizers::Tokenizer;

use crate::chat::{Chat, ChatRole};
use crate::token_string::{IntoTokenString, TokenString};

pub const MAX_TOKENS: usize = 2048;

#[derive(Clone)]
pub struct Model {
    model_type: ModelType,
    config: PhiConfig,
    vb: VarBuilder<'static>,
    tokenizer: Tokenizer,
    vocab_size: usize,
    device: Device,
    seed: u64,
}

impl Model {
    pub fn new(model_type: ModelType, seed: u64, use_cuda: bool) -> Result<Self> {
        let device = if use_cuda && candle_core::utils::cuda_is_available() {
            Device::new_cuda(0).unwrap()
        } else {
            Device::Cpu
        };
        let api = Api::new()?;
        let repo = api.model(model_type.repo_name().to_string());
        let tokenizer_filename = repo.get(model_type.tokenizer_json_name())?;
        let model_filename = repo.get(model_type.model_name())?;

        // Create model config
        let config_filename = repo.get("config.json")?;
        let config = std::fs::read_to_string(config_filename)?;
        let config = serde_json::from_str(&config)?;

        // Create VarBuilder
        let vb =
            unsafe { VarBuilder::from_mmaped_safetensors(&[model_filename], DType::F32, &device)? };

        // Create tokenizer
        let tokenizer = Tokenizer::from_file(tokenizer_filename).map_err(E::msg)?;
        let vocab_size = tokenizer.get_vocab_size(false);

        Ok(Self {
            model_type,
            config,
            vb,
            tokenizer,
            device: device.clone(),
            vocab_size,
            seed,
        })
    }

    pub fn seed(&self) -> u64 {
        self.seed
    }

    pub fn set_seed(&mut self, seed: u64) {
        self.seed = seed;
    }

    pub fn max_tokens(&self) -> usize {
        MAX_TOKENS
    }

    pub fn new_token_string(&self) -> TokenString {
        TokenString::new(Vec::new(), self.clone())
    }

    pub fn tokenize_str(&self, text: impl Display) -> TokenString {
        // Tokenize the text
        let tokens = self.tokenizer.encode(text.to_string(), true).unwrap();

        // Get the token ids
        let token_ids = tokens.get_ids().to_vec();
        TokenString::new(token_ids, self.clone())
    }

    pub fn tokenize(&self, text: impl IntoTokenString) -> TokenString {
        text.into_token_string(self)
    }

    pub(crate) fn detokenize(&self, tokens: impl AsRef<[u32]>) -> String {
        // Decode the tokens into a string
        let text = self
            .tokenizer
            .decode(tokens.as_ref(), true)
            .map_err(E::msg)
            .unwrap();
        text
    }

    /// Attempt to get the token for a given string
    pub(crate) fn get_token(&self, s: impl Display) -> Result<u32> {
        match self.tokenizer.get_vocab(true).get(&s.to_string()) {
            Some(token) => Ok(*token),
            None => anyhow::bail!("cannot find the token for {:?}", s.to_string()),
        }
    }

    /// Get an iterator that yields tokens generated by the model.
    /// Returns an error if the prompt is empty.
    pub fn infer_iter(
        &self,
        prompt: impl IntoTokenString,
        seed: u64,
        temp: Option<f64>,
        top_p: Option<f64>,
        repeat_penalty: f32,
        repeat_last_n: usize,
    ) -> Result<InferIter> {
        // Add the model seed to the seed provided
        let seed = seed.wrapping_add(self.seed);

        // Tokenize the prompt
        let prompt = self.tokenize(prompt);

        // Fail if the prompt is empty
        if prompt.is_empty() {
            anyhow::bail!("prompt was empty")
        }

        // Create pipeline
        let pipeline = Phi::new(&self.config, self.vb.clone()).unwrap();

        // Create logits processor
        let logits_processor = LogitsProcessor::new(seed, temp, top_p);

        // Get the end of text token
        let eos_token = self.get_token("<|endoftext|>").unwrap();

        // Create the iterator
        Ok(InferIter::new(
            self.device.clone(),
            prompt,
            self.vocab_size,
            pipeline,
            logits_processor,
            repeat_penalty,
            repeat_last_n,
            eos_token,
        ))
    }

    /// Generate a response based on the instruction.
    /// Returns an iterator that can be used to get the tokens generated by the model.
    pub fn instruct(
        &self,
        instruction: impl AsRef<str>,
        extra_data: Option<&HashMap<String, InferValue>>,
        seed: u64,
        temp: Option<f64>,
        top_p: Option<f64>,
        repeat_penalty: f32,
        repeat_last_n: usize,
    ) -> InferIter {
        // Create the prompt
        let prompt = self
            .model_type
            .create_instruct_prompt(instruction, extra_data);

        // Begin inference
        self.infer_iter(prompt, seed, temp, top_p, repeat_penalty, repeat_last_n)
            .unwrap()
    }

    /// Generate a response message based on the chat history.
    pub fn chat(
        &self,
        chat: &Chat,
        seed: u64,
        temp: Option<f64>,
        top_p: Option<f64>,
        repeat_penalty: f32,
        repeat_last_n: usize,
    ) -> InferIter {
        let prompt = self.model_type.create_chat_prompt(chat);
        self.infer_iter(prompt, seed, temp, top_p, repeat_penalty, repeat_last_n)
            .unwrap()
    }

    /// Generate a string similar to the given example strings.
    pub fn generate_similar(
        &self,
        desired_traits: impl Display,
        examples: &[impl Display],
        seed: u64,
        temp: Option<f64>,
        top_p: Option<f64>,
        repeat_penalty: f32,
        repeat_last_n: usize,
    ) -> String {
        const EXAMPLE_DROP_RATE: f64 = 0.25;
        const MIN_EXAMPLES: usize = 2;

        // Convert the examples to strings
        let mut examples: Vec<String> = examples.iter().map(|e| e.to_string()).collect();

        // If temp is provided, or EXAMPLE_DROP_RATE is larger than 0.0, shuffle the examples by sorting by random values generated from the seed
        // This should help introduce more variety if desired
        if temp.is_some() || EXAMPLE_DROP_RATE > 0.0 {
            let mut example_drop_seed = seed;
            examples.sort_by_key(|_| {
                let key = example_drop_seed.into_random::<u32>();
                example_drop_seed = example_drop_seed.wrapping_add(1);
                key
            });
        }

        // Optionally drop some of the examples based on EXAMPLE_DROP_RATE
        if EXAMPLE_DROP_RATE > 0.0 {
            // Calculate the number of examples to keep based on the drop rate
            let number_to_keep = (((1.0 - EXAMPLE_DROP_RATE) * examples.len() as f64).floor()
                as usize)
                .max(MIN_EXAMPLES);

            // Keep only the first `number_to_keep` examples
            examples.truncate(number_to_keep);
        }

        // Create the chat with the desired traits and examples given as chat messages
        let mut chat = Chat::new(Some("You are an assistant who generates a list of items based on the user's request. Be brief and concise.".to_string()));
        chat.add_message(
            ChatRole::User,
            format!(
                "I'm looking for a list of things that could be described as \"{}\"",
                desired_traits
            ),
        );
        for example in examples {
            chat.add_message(ChatRole::Model, example);
        }

        self.chat(&chat, seed, temp, top_p, repeat_penalty, repeat_last_n)
            .complete(&["\n"])
            .0
    }

    /// Given a list of items and a context string, try to choose the most appropriate item
    /// based on the context.
    /// Returns the chosen item (lowercased and trimmed) if successful, otherwise None.
    pub fn try_choose_item(
        &self,
        desired_traits: impl Display,
        items: impl IntoIterator<Item = impl Display>,
        seed: u64,
        temp: f64,
        attempts: usize,
    ) -> Option<String> {
        // Make sure that seed + attempts doesn't overflow by subtracting u64::MAX / 2
        let seed = if seed > u64::MAX - attempts as u64 {
            seed - u64::MAX / 2
        } else {
            seed
        };

        // Trim and lowercase all the items
        let items: Vec<String> = items
            .into_iter()
            .map(|item| item.to_string().trim().to_lowercase())
            .collect();

        // Join the items into a comma-separated list
        let items_string = items.join(", ");

        // Create the chat with the context, desired traits, and items
        let mut chat = Chat::new(None);

        // Add the user's messages with the desired traits and items
        chat.add_message(ChatRole::User, format!("List of items: {}", items_string));
        chat.add_message(
            ChatRole::User,
            format!(
                "Please select the item from the list which most fits the description: \"{}\"",
                desired_traits
            ),
        );

        // Create the prompt from the chat
        let mut prompt = self.model_type.create_chat_prompt(&chat);

        // Append a " to the end of the prompt to encourage the model to name an item in quotes
        prompt.push_str(format!("The most fitting item is: ").as_str());

        // Keep trying until the model chooses an item, incrementing the seed each time
        // After each attempt, temperature is increased to encourage diversity
        let mut response = None;
        let mut temperature = temp;
        for seed in seed..seed + attempts as u64 {
            // Clone the items
            let mut possible_items = items.clone();

            // Begin inference
            let mut inference = self
                .infer_iter(prompt.clone(), seed, Some(temperature), None, 1.0, 0)
                .unwrap();

            // Infer while possible_items > 1
            let mut inferred = String::new();
            while possible_items.len() > 1 {
                // Attempt to get the next token and check if it matches any of the possible items
                if let Some(next_token) = inference.next_token() {
                    // Add the token to the inferred string
                    inferred.push_str(&self.detokenize(&[next_token]));

                    // Remove the item from the list if it doesn't begin with the inferred string
                    let formatted = inferred.trim().to_lowercase();
                    possible_items.retain(|item| item.starts_with(&formatted));
                }
                // If there are no more tokens, empty the possible items and break
                else {
                    possible_items.clear();
                    break;
                }
            }

            // If there is only one item left, return it
            if possible_items.len() == 1 {
                response = Some(possible_items.pop().unwrap());
                break;
            }

            // Raise the temperature and try again
            temperature += 0.2;
        }

        // Return the response
        response
    }

    /// Infer a value for the given key if it were in in the given key-value pairs.
    pub fn infer_key_value<'a, V, M>(
        &self,
        kvp: M,
        key: &str,
        seed: u64,
        temp: f64,
    ) -> Result<InferValue>
    where
        V: Into<InferValue> + Clone + 'a,
        M: IntoIterator<Item = (&'a String, &'a V)>,
    {
        // Format the key-value pairs as a string to be used in the prompt.
        // We make it resemble python dictionary syntax for the model's sake.
        let hashmap_string = format!(
            "{{\n{}\n}}",
            kvp.into_iter()
                .map(|(k, v)| format!("'{}':{:?}", k, v.clone().into().to_string()))
                .collect::<Vec<_>>()
                .join(",\n")
        );

        // Create the instruction prompt
        let instruction = format!(
            "Given the following dictionary, what should the value for key '{}' be?",
            key
        );

        // We want to start the result with the key and ':' to encourage the model
        let mut prompt_extra: HashMap<String, InferValue> = HashMap::new();
        prompt_extra.insert("Response".to_string(), format!("'{}':", key).into());

        // Supply the dictionary as extra context to the model
        prompt_extra.insert("Dictionary".to_string(), hashmap_string.into());

        // Instruct the model and get the result
        let result = self
            .instruct(
                instruction,
                Some(&prompt_extra),
                seed,
                Some(temp),
                None,
                1.0,
                0,
            )
            .complete(&["\n", ",", "}"])
            .0
            .trim()
            .to_string();

        // If the result is empty, return an error
        if result.is_empty() {
            return Err(anyhow::anyhow!(
                "Model inferred empty value for key \"{}\"",
                key
            ));
        }

        InferValue::from_str(&result)
    }

    /// Infer a value for the given key if it were in in the given key-value pairs.
    /// Attempts a given number of times, with a failure being if the value fails to parse
    pub fn try_infer_key_value<'a, V, M, R>(
        &self,
        kvp: M,
        key: &str,
        seed: u64,
        temp: f64,
        attempts: usize,
    ) -> Result<R>
    where
        V: Into<InferValue> + Clone + 'a,
        M: IntoIterator<Item = (&'a String, &'a V)> + Clone,
        InferValue: TryInto<R>,
    {
        let kvp: Vec<_> = kvp.into_iter().collect();
        for idx in 0..attempts {
            // Try to infer the value for the given key
            if let Ok(value) =
                self.infer_key_value(kvp.clone(), key, seed.wrapping_add(idx as u64), temp)
            {
                // Try to convert the inferred value to the desired type
                // If the conversion was successful, return the converted value
                let attempted_conversion = value.try_into();
                if let Ok(converted) = attempted_conversion {
                    return Ok(converted);
                }
            }
        }
        Err(anyhow::anyhow!(
            "Failed to infer value for key \"{}\" after {} attempts",
            key,
            attempts
        ))
    }
}

/// Represents the type of Phi model to use.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ModelType {
    // PhiHermes,
    Phi15Instruct,
}

impl ModelType {
    pub fn repo_name(&self) -> &'static str {
        match self {
            // ModelType::PhiHermes => "lmz/candle-quantized-phi",
            ModelType::Phi15Instruct => "rasyosef/Phi-1_5-Instruct-v0.1",
        }
    }

    pub fn tokenizer_json_name(&self) -> &'static str {
        match self {
            // ModelType::PhiHermes => "tokenizer-puffin-phi-v2.json",
            ModelType::Phi15Instruct => "tokenizer.json",
        }
    }

    pub fn model_name(&self) -> &'static str {
        match self {
            // ModelType::PhiHermes => "model-phi-hermes-1_3B.safetensors",
            ModelType::Phi15Instruct => "model.safetensors",
        }
    }

    /// Creates an instruction prompt meant for this type of Phi model.
    pub fn create_instruct_prompt(
        &self,
        instruction: impl AsRef<str>,
        extra_data: Option<&HashMap<String, InferValue>>,
    ) -> String {
        match self {
            // ModelType::PhiHermes => Self::create_phi_hermes_instruct_prompt(instruction, extra_data),
            ModelType::Phi15Instruct => {
                Self::create_phi15_instruct_instruct_prompt(instruction, extra_data)
            }
        }
    }

    /*
    fn create_phi_hermes_instruct_prompt(
        instruction: impl AsRef<str>,
        extra_data: Option<&HashMap<String, InferValue>>,
    ) -> String {
        let mut prompt = String::new();

        // Add the extra data to the prompt
        if let Some(extra_data) = extra_data {
            // For each key-value pair, add it to the prompt
            for (key, value) in extra_data {
                // Skip the "Response" key
                if *key == "Response" {
                    continue;
                }
                prompt.push_str(&format!("### {}:\n{}\n", key, value));
            }
        }

        // Add the instruction to the prompt
        prompt.push_str(&format!("### Instruction:\n{}\n", instruction.as_ref()));

        // Ask the model to generate the response
        prompt.push_str("### Response:\n");

        // If extra_data has a "Response" key, add it to the prompt
        if let Some(response) = extra_data.and_then(|h| h.get("Response")) {
            prompt.push_str(&response.to_string());
        }

        prompt
    }
    */

    fn create_phi15_instruct_instruct_prompt(
        instruction: impl AsRef<str>,
        extra_data: Option<&HashMap<String, InferValue>>,
    ) -> String {
        let mut prompt = String::new();

        // Start the system section
        prompt.push_str("<|im_start|>system\n");

        // Get the role from extra_data if it exists
        // Otherwise default to a default role
        let role = extra_data
            .and_then(|h| h.get("Role"))
            .map(|s| s.to_string())
            .unwrap_or("You are a helpful assistant. Be concise and to the point but provide enough detail to be useful. Explain your thinking where appropriate.".to_string());

        // Push the role to the system section
        prompt.push_str(&format!("{}\n", role));

        // Push other extra data to the system section
        // Skip the "Role" and "Response" keys
        if let Some(extra_data) = extra_data
            && !extra_data.is_empty()
        {
            // First start with "What you know:" in case that helps the model
            prompt.push_str("What you know:\n");

            // Add the other extra data to the system section
            for (key, value) in extra_data {
                if key != "Role" && key != "Response" {
                    prompt.push_str(&format!("{}: {}\n", key, value));
                }
            }
        }

        // End the system section and start the user section
        prompt.push_str("<|im_end|>\n<|im_start|>user\n");

        // Push the instruction as the user section
        prompt.push_str(&format!("{}\n", instruction.as_ref()));

        // End the user section and start the assistant section (response)
        prompt.push_str("<|im_end|>\n<|im_start|>assistant\n");

        // Start the response with the value of extra_data["Response"] if it exists
        if let Some(response) = extra_data.and_then(|h| h.get("Response")) {
            prompt.push_str(&response.to_string());
        }

        prompt
    }

    /// Creates a chat prompt meant for this type of Phi model.
    pub fn create_chat_prompt(&self, chat: &Chat) -> String {
        match self {
            // ModelType::PhiHermes => Self::create_phi_hermes_chat_prompt(chat),
            ModelType::Phi15Instruct => Self::create_phi15_instruct_chat_prompt(chat),
        }
    }

    fn create_phi15_instruct_chat_prompt(chat: &Chat) -> String {
        let mut prompt = String::new();

        // Add the system prompt to the system section
        prompt.push_str(&format!(
            "<|im_start|>system\n{}\n<|im_end|>\n",
            chat.system_prompt()
        ));

        // Add each message in the chat to the prompt as a new section
        for message in chat {
            match message.sender() {
                ChatRole::User => {
                    prompt.push_str(&format!(
                        "<|im_start|>user\n{}\n<|im_end|>\n",
                        message.content()
                    ));
                }
                ChatRole::Model => {
                    prompt.push_str(&format!(
                        "<|im_start|>assistant\n{}\n<|im_end|>\n",
                        message.content()
                    ));
                }
            }
        }

        // Start the final assistant section (response)
        prompt.push_str("<|im_start|>assistant\n");

        prompt
    }
}

pub struct InferIter {
    device: Device,
    tokens: TokenString,
    vocab_size: usize,
    step: usize,
    pipeline: Phi,
    logits_processor: LogitsProcessor,
    repeat_penalty: f32,
    repeat_last_n: usize,
    eos_token: u32,
    reached_eos: bool,
}

impl InferIter {
    pub(crate) fn new(
        device: Device,
        tokens: TokenString,
        vocab_size: usize,
        pipeline: Phi,
        logits_processor: LogitsProcessor,
        repeat_penalty: f32,
        repeat_last_n: usize,
        eos_token: u32,
    ) -> Self {
        Self {
            device,
            tokens,
            vocab_size,
            step: 0,
            pipeline,
            logits_processor,
            repeat_penalty,
            repeat_last_n,
            eos_token,
            reached_eos: false,
        }
    }

    pub fn next_token(&mut self) -> Option<u32> {
        // Exit early if we already got the end of text token
        if self.reached_eos {
            return None;
        }

        // Get the context size for this step
        let context_size = if self.step > 0 { 1 } else { self.tokens.len() };

        // Get the context
        let context = self
            .tokens
            .get(self.tokens.len().saturating_sub(context_size)..)
            .unwrap();

        // Create the input tensor containing the context
        let input = Tensor::new(context, &self.device)
            .unwrap()
            .unsqueeze(0)
            .unwrap();

        // Forward the input through the pipeline
        let logits = self.pipeline.forward(&input).unwrap();

        // Get the logits
        let logits = logits.squeeze(0).unwrap().to_dtype(DType::F32).unwrap();

        // Apply the repeat penalty
        let logits = if self.repeat_penalty == 1.0 || self.repeat_last_n == 0 {
            logits
        } else {
            // Apply the repeat penalty to the last repeat_last_n tokens
            let start_at = self.tokens.len().saturating_sub(self.repeat_last_n);
            candle_transformers::utils::apply_repeat_penalty(
                &logits,
                self.repeat_penalty,
                self.tokens.get(start_at..).unwrap(),
            )
            .unwrap()
        };

        // Sample the next token
        let next_token = self.logits_processor.sample(&logits).unwrap();

        // Increment the step
        self.step += 1;

        // If the token is not the end of text token, add it to the tokens
        if next_token != self.eos_token {
            self.tokens.push_token(next_token);
        }
        // Otherwise, set reached_eos to true and return None
        else {
            self.reached_eos = true;
            return None;
        }

        // Return the next token
        Some(next_token)
    }

    /// Run the iterator until completion or until one of `end_sequences` is generated
    /// and return everything up to that point as a `String`, as well as the end sequence that was reached
    pub fn complete<'a>(mut self, end_sequences: &'a [&str]) -> (String, Option<&'a str>) {
        let mut response = String::new();
        while let Some(token) = self.next_token()
            && token < self.vocab_size as u32 - 1
        {
            let token_str = self.tokens.model.detokenize(&[token]);
            // Exit early if token_str formed any stop sequence, cutting off the response at that point
            for end_sequence in end_sequences {
                if let Some(pos) = token_str.find(end_sequence) {
                    response.push_str(&token_str[..pos]);
                    self.reached_eos = true;
                    return (response, Some(end_sequence));
                }
            }

            response.push_str(&token_str);
        }

        self.reached_eos = true;

        (response, None)
    }
}

impl Into<String> for InferIter {
    fn into(self) -> String {
        self.complete(&[]).0
    }
}

#[derive(Clone)]
pub enum InferValue {
    String(String),
    Float(f64),
    Int(i64),
}

impl InferValue {
    /// Convert the `InferValue` to a simple `String`
    pub fn to_string(&self) -> String {
        match self {
            Self::String(s) => s.clone(),
            Self::Float(f) => f.to_string(),
            Self::Int(i) => i.to_string(),
        }
    }

    /// Parse a `&str` to an `InferValue`
    pub fn from_str(s: &str) -> Result<Self> {
        if let Ok(f) = s.parse::<f64>() {
            Ok(Self::Float(f))
        } else if let Ok(i) = s.parse::<i64>() {
            Ok(Self::Int(i))
        } else {
            Ok(Self::String(s.to_string().trim_matches('"').to_string()))
        }
    }

    /// Write a debug representation of the `InferValue`.
    /// This is the same as the value would appear in code.
    pub fn write_debug(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(s) => write!(f, "\"{}\"", s),
            Self::Float(fl) => write!(f, "{}", fl),
            Self::Int(i) => write!(f, "{}", i),
        }
    }
}

impl FromStr for InferValue {
    type Err = E;

    fn from_str(s: &str) -> Result<Self> {
        InferValue::from_str(s)
    }
}

impl Display for InferValue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.to_string())
    }
}

impl Debug for InferValue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.write_debug(f)
    }
}

impl From<String> for InferValue {
    fn from(s: String) -> Self {
        Self::String(s)
    }
}

impl From<&str> for InferValue {
    fn from(s: &str) -> Self {
        Self::String(s.to_owned())
    }
}

impl From<f64> for InferValue {
    fn from(f: f64) -> Self {
        Self::Float(f)
    }
}

impl From<i64> for InferValue {
    fn from(i: i64) -> Self {
        Self::Int(i)
    }
}

impl From<f32> for InferValue {
    fn from(f: f32) -> Self {
        Self::Float(f as f64)
    }
}

impl From<i32> for InferValue {
    fn from(i: i32) -> Self {
        Self::Int(i as i64)
    }
}

impl From<u32> for InferValue {
    fn from(i: u32) -> Self {
        Self::Int(i as i64)
    }
}

impl From<i16> for InferValue {
    fn from(i: i16) -> Self {
        Self::Int(i as i64)
    }
}

impl From<u16> for InferValue {
    fn from(i: u16) -> Self {
        Self::Int(i as i64)
    }
}

impl From<i8> for InferValue {
    fn from(i: i8) -> Self {
        Self::Int(i as i64)
    }
}

impl From<u8> for InferValue {
    fn from(i: u8) -> Self {
        Self::Int(i as i64)
    }
}

impl From<usize> for InferValue {
    fn from(i: usize) -> Self {
        Self::Int(i as i64)
    }
}

impl From<isize> for InferValue {
    fn from(i: isize) -> Self {
        Self::Int(i as i64)
    }
}

impl<T: Into<InferValue> + Clone> From<&T> for InferValue {
    fn from(value: &T) -> Self {
        value.clone().into()
    }
}

impl Into<String> for InferValue {
    fn into(self) -> String {
        match self {
            InferValue::String(s) => {
                // Remove surrounding quotes (both ' and ")
                s.trim_matches(|c| c == '"' || c == '\'').to_string()
            }
            InferValue::Float(f) => f.to_string(),
            InferValue::Int(i) => i.to_string(),
        }
    }
}

impl TryInto<f64> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<f64, Self::Error> {
        match self {
            InferValue::Float(f) => Ok(f),
            InferValue::Int(i) => Ok(i as f64),
            InferValue::String(s) => s.parse::<f64>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<i64> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<i64, Self::Error> {
        match self {
            InferValue::Int(i) => Ok(i),
            InferValue::Float(f) => Ok(f as i64),
            InferValue::String(s) => s.parse::<i64>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<u64> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<u64, Self::Error> {
        match self {
            InferValue::Int(i) => Ok(i as u64),
            InferValue::Float(f) => Ok(f as u64),
            InferValue::String(s) => s.parse::<u64>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<f32> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<f32, Self::Error> {
        match self {
            InferValue::Float(f) => Ok(f as f32),
            InferValue::Int(i) => Ok(i as f32),
            InferValue::String(s) => s.parse::<f32>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<i32> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<i32, Self::Error> {
        match self {
            InferValue::Int(i) => i
                .try_into()
                .map_err(|_| anyhow::anyhow!("Failed to convert i64 to i32")),
            InferValue::Float(f) => Ok(f as i32),
            InferValue::String(s) => s.parse::<i32>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<u32> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<u32, Self::Error> {
        match self {
            InferValue::Int(i) => i
                .try_into()
                .map_err(|_| anyhow::anyhow!("Failed to convert i64 to u32")),
            InferValue::Float(f) => Ok(f as u32),
            InferValue::String(s) => s.parse::<u32>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<i16> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<i16, Self::Error> {
        match self {
            InferValue::Int(i) => i
                .try_into()
                .map_err(|_| anyhow::anyhow!("Failed to convert i64 to i16")),
            InferValue::Float(f) => Ok(f as i16),
            InferValue::String(s) => s.parse::<i16>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<u16> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<u16, Self::Error> {
        match self {
            InferValue::Int(i) => i
                .try_into()
                .map_err(|_| anyhow::anyhow!("Failed to convert i64 to u16")),
            InferValue::Float(f) => Ok(f as u16),
            InferValue::String(s) => s.parse::<u16>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<i8> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<i8, Self::Error> {
        match self {
            InferValue::Int(i) => i
                .try_into()
                .map_err(|_| anyhow::anyhow!("Failed to convert i64 to i8")),
            InferValue::Float(f) => Ok(f as i8),
            InferValue::String(s) => s.parse::<i8>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<u8> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<u8, Self::Error> {
        match self {
            InferValue::Int(i) => i
                .try_into()
                .map_err(|_| anyhow::anyhow!("Failed to convert i64 to u8")),
            InferValue::Float(f) => Ok(f as u8),
            InferValue::String(s) => s.parse::<u8>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<isize> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<isize, Self::Error> {
        match self {
            InferValue::Int(i) => i
                .try_into()
                .map_err(|_| anyhow::anyhow!("Failed to convert i64 to isize")),
            InferValue::Float(f) => Ok(f as isize),
            InferValue::String(s) => s.parse::<isize>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

impl TryInto<usize> for InferValue {
    type Error = anyhow::Error;

    fn try_into(self) -> Result<usize, Self::Error> {
        match self {
            InferValue::Int(i) => i
                .try_into()
                .map_err(|_| anyhow::anyhow!("Failed to convert i64 to usize")),
            InferValue::Float(f) => Ok(f as usize),
            InferValue::String(s) => s.parse::<usize>().map_err(|e| anyhow::anyhow!(e)),
        }
    }
}

#[macro_export]
macro_rules! data_map {
    [$($key:expr => $value:expr),*$(,)?] => {
        {
            #[allow(unused_mut)]
            let mut map: std::collections::HashMap<String, $crate::model::InferValue> = std::collections::HashMap::new();
            $(
                map.insert($key.to_string(), $crate::model::InferValue::from($value));
            )*
            map
        }
    };
}
